---
ID: "<%= Id %>"
Parent: "30d1750f-6aba-4cbd-bdc3-08d23f620068"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/<%= Parameters.ModuleName %>
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190213T021150Z
