Generators:
  - name: 'SolutionPrefix'
    value: 'Helix'
    exclude: false
  - name: 'SitecoreVersion'
    value: '9.0.2'
    exclude: false
  - name: 'SolutionName'
    value: 'Helix'
    exclude: false
  - name: 'EnvironmentUrl'
    value: 'https://starterkit.sc/'
    exclude: false
  - name: 'EnvironmentRoot'
    value: 'c:\inetpub\wwwroot\starterkit.sc'
    exclude: false
  - name: 'SolutionType'
    value: 'Base'
    exclude: false
  - name: 'ModuleName'
    exclude: true
  - name: 'GeneratorType'
    exclude: true
  - name: 'GeneratorModuleType'
    exclude: true
  - name: 'WebsiteName'
    exclude: true